export const ActionTypes = {
  POST_USER: "POST_USER",
  GET_USERS: "GET_USERS",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  SELECTED_USER: "SELECTED_USER",

  CREATE_POST: "POST_USER",
  GET_POSTS: "GET_POSTS",
  UPDATE_POST: "UPDATE_POST",
  DELETE_POST: "DELETE_POST",
  SELECTED_POST: "SELECTED_POST",

  CREATE_ALBUM: "CREATE_ALBUM",
  GET_ALBUMS: "GET_ALBUMS",
  UPDATE_ALBUM: "UPDATE_ALBUM",
  DELETE_ALBUM: "DELETE_ALBUM",
  SELECTED_ALBUM: "SELECTED_ALBUM",
};
