export const ActionTypes = {
  POST_USER: "POST_USER",
  GET_USERS: "GET_USERS",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  SELECTED_USER: "SELECTED_USER",

  CREATE_POST: "POST_USER",
  GET_POSTS: "GET_POSTS",
  UPDATE_POST: "UPDATE_POST",
  DELETE_POST: "DELETE_POST",
  SELECTED_POST: "SELECTED_POST",

  CREATE_ALBUM: "CREATE_ALBUM",
  GET_ALBUMS: "GET_ALBUMS",
  UPDATE_ALBUM: "UPDATE_ALBUM",
  DELETE_ALBUM: "DELETE_ALBUM",
  SELECTED_ALBUM: "SELECTED_ALBUM",

  POST_PHOTO: "POST_PHOTO",
  GET_PHOTOS: "GET_PHOTOS",
  UPDATE_PHOTO: "UPDATE_PHOTO",
  DELETE_PHOTO: "DELETE_PHOTO",
  SELECTED_PHOTO: "SELECTED_PHOTO",

  CREATE_TODO: "CREATE_TODO",
  GET_TODOS: "GET_TODOS",
  UPDATE_TODO: "UPDATE_TODO",
  DELETE_TODO: "DELETE_TODO",
  SELECTED_TODO: "SELECTED_TODO",
};
